version: '3'

# TruthGraph Task Runner
# Requires: go-task (https://taskfile.dev)
# Install: winget install Task.Task

vars:
  PYTHON: python
  PYMARKDOWNLNT: pymarkdownlnt.exe
  RUFF: ruff

tasks:
  # ============================================================================
  # Linting Tasks
  # ============================================================================

  lint:
    desc: Run all linters (pymarkdownlnt + ruff)
    cmds:
      - task: lint:markdown
      - task: lint:python

  lint:markdown:
    desc: Lint Markdown files with pymarkdownlnt (excluding .claude/)
    cmds:
      - powershell -NoProfile -ExecutionPolicy Bypass -File scripts/lint-markdown.ps1
    sources:
      - '**/*.md'

  lint:python:
    desc: Lint Python code with ruff
    cmds:
      - '{{.RUFF}} check'
    sources:
      - '**/*.py'
      - pyproject.toml

  lint:fix:
    desc: Auto-fix all linting issues (pymarkdownlnt + ruff)
    cmds:
      - task: lint:fix:markdown
      - task: lint:fix:python

  lint:fix:markdown:
    desc: Auto-fix Markdown linting issues with pymarkdownlnt (excluding .claude/)
    cmds:
      - powershell -NoProfile -ExecutionPolicy Bypass -File scripts/lint-markdown-fix.ps1
    sources:
      - '**/*.md'

  lint:fix:python:
    desc: Auto-fix Python linting issues with ruff
    cmds:
      - '{{.RUFF}} check --fix'
      - '{{.RUFF}} format'
    sources:
      - '**/*.py'
      - pyproject.toml

  # ============================================================================
  # Docker Development Tasks
  # ============================================================================

  setup:
    desc: Setup development environment (create .env, build containers)
    cmds:
      - cmd: powershell -Command "if (!(Test-Path .env)) { Copy-Item .env.example .env }"
        platforms: [windows]
      - cmd: test -f .env || cp .env.example .env
        platforms: [linux, darwin]
      - docker-compose build
      - echo "✓ Setup complete! Run task dev to start services"

  dev:
    desc: Start development environment (htmx frontend only)
    cmds:
      - docker-compose up -d postgres api frontend
      - echo "✓ Services starting..."
      - echo "  PostgreSQL at localhost:5432"
      - echo "  API at http://localhost:8000"
      - echo "  Frontend (htmx) at http://localhost:5000"
      - echo "  API Docs at http://localhost:8000/docs"
      - echo "Run task logs to view logs"

  dev:react:
    desc: Start development environment with React frontend
    cmds:
      - docker-compose --profile react up -d
      - echo "✓ Services starting..."
      - echo "  PostgreSQL at localhost:5432"
      - echo "  API at http://localhost:8000"
      - echo "  Frontend (htmx) at http://localhost:5000"
      - echo "  Frontend (React) at http://localhost:5173"
      - echo "  API Docs at http://localhost:8000/docs"

  down:
    desc: Stop and remove containers
    cmds:
      - docker-compose down
      - echo "✓ Services stopped"

  restart:
    desc: Restart all services
    cmds:
      - task: down
      - task: dev

  reset:
    desc: Reset everything (destructive - removes volumes)
    cmds:
      - docker-compose down -v
      - cmd: powershell -Command "if (Test-Path .volumes) { Remove-Item -Recurse -Force .volumes }"
        platforms: [windows]
        ignore_error: true
      - cmd: rm -rf .volumes
        platforms: [linux, darwin]
        ignore_error: true
      - echo "✓ Reset complete. Run task setup to start fresh"

  logs:
    desc: View logs from all services
    cmds:
      - docker-compose logs -f

  logs:api:
    desc: View API logs only
    cmds:
      - docker-compose logs -f api

  logs:db:
    desc: View database logs only
    cmds:
      - docker-compose logs -f postgres

  shell:
    desc: Open shell in API container
    cmds:
      - docker-compose exec api bash

  shell:db:
    desc: Open PostgreSQL shell
    cmds:
      - docker-compose exec postgres psql -U truthgraph -d truthgraph

  # ============================================================================
  # Database Tasks
  # ============================================================================

  db:migrate:
    desc: Run database migrations (Alembic)
    cmds:
      - docker-compose exec api alembic upgrade head
      - echo "✓ Database migrations applied"

  db:migrate:down:
    desc: Rollback last database migration
    cmds:
      - docker-compose exec api alembic downgrade -1
      - echo "✓ Last migration rolled back"

  db:migrate:status:
    desc: Show current migration status
    cmds:
      - docker-compose exec api alembic current

  db:migrate:history:
    desc: Show migration history
    cmds:
      - docker-compose exec api alembic history

  db:migrate:create:
    desc: Create a new migration (MIGRATION_NAME required)
    cmds:
      - docker-compose exec api alembic revision --autogenerate -m "{{.MIGRATION_NAME}}"

  # ============================================================================
  # Testing Tasks
  # ============================================================================

  test:
    desc: Run all tests
    cmds:
      - task: test:unit
      - task: test:integration

  test:unit:
    desc: Run unit tests only
    cmds:
      - docker-compose exec api pytest tests/unit tests/services -v -m "not integration"

  test:integration:
    desc: Run integration tests only
    cmds:
      - docker-compose exec api pytest tests/integration -v

  test:ml:
    desc: Run ML service tests (embedding, NLI, vector search)
    cmds:
      - docker-compose exec api pytest tests/services/ml tests/integration/test_*_integration.py -v

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - docker-compose exec api pytest --cov=truthgraph --cov-report=html --cov-report=term

  # ============================================================================
  # ML Service Tasks
  # ============================================================================

  ml:warmup:
    desc: Warmup ML models (download and cache)
    cmds:
      - docker-compose exec api python -c "from truthgraph.services.ml.model_cache import ModelCache; ModelCache.get_instance().warmup_all_models()"
      - echo "✓ ML models warmed up and cached"

  ml:benchmark:
    desc: Run ML performance benchmarks
    cmds:
      - task: ml:benchmark:embedding
      - task: ml:benchmark:nli
      - task: ml:benchmark:vector

  ml:benchmark:embedding:
    desc: Benchmark embedding service
    cmds:
      - docker-compose exec api python scripts/benchmark_embeddings.py

  ml:benchmark:nli:
    desc: Benchmark NLI service
    cmds:
      - docker-compose exec api python scripts/benchmark_nli.py

  ml:benchmark:vector:
    desc: Benchmark vector search
    cmds:
      - docker-compose exec api python scripts/benchmark_vector_search.py

  ml:benchmark:e2e:
    desc: Benchmark end-to-end pipeline
    cmds:
      - docker-compose exec api python scripts/test_e2e_performance.py --warmup

  ml:profile:
    desc: Profile ML services for bottlenecks
    cmds:
      - docker-compose exec api python scripts/profile_ml_services.py

  ml:optimize:
    desc: Optimize batch sizes for current hardware
    cmds:
      - docker-compose exec api python scripts/optimize_batch_sizes.py

  # ============================================================================
  # GPU Support Tasks
  # ============================================================================

  dev:gpu:
    desc: Start development environment with GPU support
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
      - echo "✓ Services starting with GPU support..."
      - echo "  PostgreSQL at localhost:5432"
      - echo "  API at http://localhost:8000"
      - echo "  API Docs at http://localhost:8000/docs"
      - echo "  GPU acceleration enabled for ML models"

  gpu:check:
    desc: Check GPU availability in container
    cmds:
      - docker-compose exec api python -c "import torch; print('CUDA available:', torch.cuda.is_available()); print('Device:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU')"

  # ============================================================================
  # Helper Tasks
  # ============================================================================

  check:
    desc: Run all checks (lint + type check + tests)
    cmds:
      - task: lint
      - echo "✓ All checks passed!"

  format:
    desc: Format all code (Python with ruff, Markdown with pymarkdownlnt fix)
    cmds:
      - task: lint:fix

  clean:
    desc: Clean up generated files and caches
    cmds:
      - rm -rf __pycache__
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache
      - rm -rf .mypy_cache
      - rm -rf dist
      - rm -rf build
      - rm -rf *.egg-info
      - echo "✓ Cleaned up caches and build artifacts"

  help:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # ============================================================================
  # Default Task
  # ============================================================================

  default:
    desc: Show help (default task when running 'task' with no arguments)
    cmds:
      - task: help
    silent: true
